apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gocd-server-pvc3
  namespace: gocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi

