apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-ebs-sc
  resources:
    requests:
      storage: 10Gi

