apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlik-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qlik-app
  template:
    metadata:
      labels:
        app: qlik-app
    spec:
      containers:
        - name: qlik-app
          image: kevalsenghani/qlik-java-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: OTEL_SERVICE_NAME
              value: "qlik-java-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.devops-tools.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://tempo.devops-tools.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_INSTRUMENTATION_LOGGING_ENABLED
              value: "true"
            - name: PYROSCOPE_APPLICATION_NAME
              value: "qlik-java-app"
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://pyroscope.devops-tools.svc.cluster.local:4040"
            - name: PYROSCOPE_FORMAT
              value: "jfr"
            - name: PYROSCOPE_PROFILING_INTERVAL
              value: "50ms"
            - name: PYROSCOPE_UPLOAD_INTERVAL
              value: "30s"
            - name: PYROSCOPE_PROFILER_ALLOC
              value: "1m"
            - name: PYROSCOPE_PROFILER_LOCK
              value: "100ms"
            - name: OTEL_PYROSCOPE_START_PROFILING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"