apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-aws-secret
  namespace: devops-tools
spec:
  provider: aws

  parameters:
    region: ap-south-1

    objects: |
      - objectName: "grafana-aws-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
          - path: "host"
            objectAlias: "host"
          - path: "database"
            objectAlias: "database"

  secretObjects:
    - secretName: grafana-db-credentials
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: host
          key: host
        - objectName: database
          key: database
