apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-provisioning
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc