apiVersion: v1
kind: ServiceAccount
metadata:
  name: gocd-agent-sa
  namespace: gocd
  app.kubernetes.io/managed-by: Helm
annotations:
  meta.helm.sh/release-name: gocd
  meta.helm.sh/release-namespace: gocd

