apiVersion: v1
kind: ServiceAccount
metadata:
  name: gocd-agent-sa
  namespace: gocd
  annotations:
    meta.helm.sh/release-name: gocd
    meta.helm.sh/release-namespace: gocd
  labels:
    app.kubernetes.io/managed-by: Helm