collector:
  enabled: true

allInOne:
  enabled: false

query:
  enabled: true

# config:
#   exporters:
#     otlp/jaeger:
#       endpoint: jaeger-collector.observability.svc.cluster.local:4317
#       tls:
#         insecure: true

#   service:
#     pipelines:
#       traces:
#         receivers: [otlp]
#         processors: [batch]
#         exporters: [otlp/jaeger]