apiVersion: 1
groups:
    - orgId: 1
      name: test
      folder: Test
      interval: 1m
      rules:
        - uid: ef693spti3qpse
          title: Test alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: df692r5h3lgxsf
              model:
                editorMode: code
                expr: up{job="kubernetes-service-endpoints"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            summary: Test
          labels:
            Application: Test
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
