{{- if .Values.otel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-shopping.fullname" . }}-collector
  labels:
    {{- include "otel-shopping.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-shopping.name" . }}-collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "otel-shopping.name" . }}-collector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otel.collector.image | quote }}
          args: ["--config=/conf/collector.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /conf
          resources:
            {{- toYaml .Values.otel.collector.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "otel-shopping.fullname" . }}-collector
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-shopping.fullname" . }}-collector
  labels:
    {{- include "otel-shopping.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: {{ .Values.otel.collector.service.port }}
      targetPort: otlp-grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "otel-shopping.name" . }}-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
