apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: devops-tools
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: MySQL
        type: mysql
        url: mysql:3306
        database: grafana
        user: grafana_user
        secureJsonData:
          password: your-password
