apiVersion: infractl/v1
kind: Application
metadata:
  name: grafana
spec:
  type: helm
  namespace: devops-tools

  source:
    repo: https://grafana.github.io/helm-charts
    chart: grafana
    version: "latest"

  valuesFiles:
    - values.yaml
    - override/values-prod.yaml
