format_version: 10
environments:
  obs-monitprod:
    environment_variables:
      GRAFANA_DB_USER: grafana_user
      GRAFANA_DB_HOST: grafana-mysql.c7goqse0ynvz.ap-south-1.rds.amazonaws.com:3306
    secure_variables:
      GRAFANA_DB_PASSWORD: AES:h+ldLVBS2M+a/RjC6nLDrg==:iPlJ7Z0OIiMQo93tdcglKQ==
      GIT_PASSWORD: AES:KGrglQ0nBsSwXnWAELnqdg==:bE/9YGCXHP/wW6mrVwgtuXuo/xCzpPSDHsz+/nH3KwsshlK2m7GK8JNhm47Ic507
    pipelines:
      - Grafana-deploy
      - Loki-deploy
      - Jaeger-Tracing-deploy
      - CertManager-deploy
      - Prometheus-deploy
      - Mimir-deploy
      - Tempo-deploy
      - Gocd-deploy