format_version: 10
environments:
  obs-monitprod:
    environment_variables:
      GRAFANA_DB_USER: grafana_user
      GRAFANA_DB_HOST: grafana-mysql.c7goqse0ynvz.ap-south-1.rds.amazonaws.com:3306
    pipelines:
      - Grafana-deploy
      - Loki-deploy