AWX:
  enabled: true
  name: awx

  spec:
    admin_user: admin

    service_type: NodePort

    ingress_type: none

    postgres_configuration_secret: awx-postgres-configuration

    projects_persistence: false
    # projects_storage_class: efs-sc
    # projects_storage_size: 5Gi

postgres:
  enabled: false
  #   host: awx-postgres.c7goqse0ynvz.ap-south-1.rds.amazonaws.com
  #   port: 5678
  #   dbName: awx
  #   username: awx
  #   password: Unset
  #   sslmode: prefer
  #   type: unmanaged



rbac:
  create: true

operator-controller: {}

operator-controller-containers: {}
