{
 "title": "Kubernetes Golden Infra Signals",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; background-color: rgb(215,215,0);padding: 10px; color: black; font-size: 22px; font-weight: bold;\">\nKubernetes Golden Infra Signals\n</div>\n\n"
   }
  },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Container",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Used %",
   "type": "timeseries",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\"}[2m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "timeseries",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(clamp_min((1 - (node_memory_MemAvailable_bytes{ job=~\"$job\"} / node_memory_MemTotal_bytes{ job=~\"$job\"})) * 100, 0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PVC Used %",
   "type": "timeseries",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max without(instance,node) (\r\n(\r\n  topk(1, kubelet_volume_stats_capacity_bytes{ job=\"kubelet\"})\r\n  -\r\n  topk(1, kubelet_volume_stats_available_bytes{ job=\"kubelet\"})\r\n)\r\n/\r\ntopk(1, kubelet_volume_stats_capacity_bytes{ job=\"kubelet\"})\r\n* 100)\r\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"text-align:center; background-color: rgb(215,215,0);padding: 10px; color: black; font-size: 20px; font-weight: bold;\">\nPod Overview\n</div>\n\n"
   }
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase{job=~\"$job\"}==1)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Stats Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (namespace, pod) (\r\n  kube_pod_container_status_last_terminated_timestamp{job=~\"$job\"}*1000\r\n)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (namespace, pod) (\r\n  kube_pod_container_status_restarts_total {job=~\"$job\"}\r\n)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (namespace, pod,phase) (\r\n  kube_pod_status_phase{job=~\"$job\"}==1\r\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<div style=\"text-align:center; background-color: rgb(215,215,0);padding: 10px; color: black; font-size: 20px; font-weight: bold;\">\nContainer Overview\n</div>\n\n"
   }
  },
  {
   "title": "Container Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (reason)(kube_pod_container_status_waiting_reason{job=~\"$job\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "count by (reason)(kube_pod_container_status_terminated_reason{job=~\"$job\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Stats Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod,container,reason) (\r\n  kube_pod_container_status_waiting_reason{job=~\"$job\"}\r\n)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (namespace, pod,container,reason) (\r\n  kube_pod_container_status_terminated_reason{job=~\"$job\"}\r\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}