apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: kevalsenghani/my-app:latest
          type: NodePort
          ports:
          - port: 80
            targetPort: 3300   # or 3300 if you changed it
            nodePort: 30007    # 👈 optional (range: 30000-32767)
            name: http
      imagePullSecrets:
        - name: dockerhub-creds
