apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: kevalsenghani/my-app:latest
          type: NodePort
          ports:
            - containerPort: 3300
      imagePullSecrets:
        - name: dockerhub-creds
