apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3300   # or 3300 if you changed it
    nodePort: 30007    # 👈 optional (range: 30000-32767)
    name: http
  selector:
    app: my-app
