apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-secret2
  namespace: devops-tools
spec:
  provider: aws

  parameters:
    region: ap-south-1

    objects: |
      - objectName: "grafana-admin-secret2"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"

  secretObjects:
    - secretName: grafana-admin-credentials
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: host
          key: host
        - objectName: database
          key: database
