apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-loki-bucket-secret
  namespace: devops-tools
spec:
  provider: aws

  parameters:
    region: ap-south-1

    objects: |
      - objectName: "grafana-loki-bucket-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "access-key"
            objectAlias: "access-key"
          - path: "access-password"
            objectAlias: "access-password"

  secretObjects:
    - secretName: grafana-loki-bucket-secret
      type: Opaque
      data:
        - objectName: access-key
          key: access-key
        - objectName: access-password
          key: access-password