image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.153.0"
  pullPolicy: IfNotPresent

mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}
    resource:
      attributes:
        - action: upsert
          key: service.name
          from_attribute: service.name

        - action: upsert
          key: k8s.namespace.name
          from_attribute: k8s.namespace.name
  exporters:
    otlp/tempo:
      endpoint: tempo.devops-tools.svc.cluster.local:4317
      tls:
        insecure: true

    otlphttp/loki:
      endpoint: http://loki.devops-tools.svc.cluster.local:3100/otlp

    prometheus:
      endpoint: "0.0.0.0:8889"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resource,batch]
        exporters: [debug,otlp/tempo]

      logs:
        receivers: [otlp]
        processors: [resource,batch]
        exporters: [debug,otlphttp/loki]

      metrics:
        receivers: [otlp]
        processors: [resource,batch]
        exporters: [prometheus]

# config:
#   exporters:
#     otlp/tempo:
#       endpoint: tempo.devops-tools.svc.cluster.local:4317
#       tls:
#         insecure: true

#   service:
#     pipelines:
#       traces:
#         exporters:
#           - debug
#           - otlp/tempo



