image:
  # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  pullPolicy: IfNotPresent
  tag: "0.153.0"


mode: "deployment"


# config:
#   exporters:
#     otlp/tempo:
#       endpoint: tempo.devops-tools.svc.cluster.local:4317
#       tls:
#         insecure: true

#   service:
#     pipelines:
#       traces:
#         exporters:
#           - debug
#           - otlp/tempo



config:
  exporters:
    otlp/tempo:
      endpoint: tempo-distributor.observability.svc.cluster.local:4317
      tls:
        insecure: true

    loki:
      endpoint: http://loki.devops-tools.svc.cluster.local/loki/api/v1/push

    prometheus:
      endpoint: "0.0.0.0:8889"

  service:
    pipelines:
      traces:
        exporters:
          - debug
          - otlp/tempo

      logs:
        exporters:
          - debug
          - loki

      metrics:
        exporters:
          - debug
          - prometheus