server:
  image:
    repository: quay.io/prometheus/prometheus
    tag: "v3.10.0"
  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  service:
    enabled: true
    servicePort: 9090
    type: NodePort

# extraScrapeConfigs: |
#   - job_name: prometheus-test2
#     static_configs:
#       - targets: ['localhost:9090']