# extraLabels: 
#   app: read-vault-secret

# command:
#   - sh
#   - -c
#   - |
#     . /vault/secrets/mysql-secret
#     exec /run.sh

# serviceAccount:
#   create: false
#   name: vault-serviceaccount
deploymentStrategy:
  type: Recreate


envValueFrom:
  GF_DATABASE_USER:
    secretKeyRef:
      name: grafana-aws-secret
      key: username
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-aws-secret
      key: password
  GF_DATABASE_HOST:
    secretKeyRef:
      name: grafana-aws-secret
      key: host
  GF_DATABASE_NAME:
    secretKeyRef:
      name: grafana-aws-secret
      key: database


vault:
  enabled: false

  # annotations:
  #   vault.hashicorp.com/agent-inject: "true"
  #   vault.hashicorp.com/role: "vault-role"
  #   vault.hashicorp.com/service: "http://vault.devops-tools.svc:8200"

  #   vault.hashicorp.com/agent-inject-secret-mysql-secret: "secret/data/mysql-secret"

  #   vault.hashicorp.com/agent-inject-template-mysql-secret: |
  #     {{- with secret "secret/data/mysql-secret" }}
  #     export GF_DATABASE_TYPE="mysql"
  #     export GF_DATABASE_HOST="{{ .Data.data.host }}"
  #     export GF_DATABASE_USER="{{ .Data.data.username }}"
  #     export GF_DATABASE_PASSWORD="{{ .Data.data.password }}"
  #     export GF_DATABASE_NAME="{{ .Data.data.database }}"
  #     {{- end }}

image:
  registry: docker.io
  repository: grafana/grafana
  tag: "12.0.0"

persistence:
  type: pvc
  enabled: true
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  finalizers:
    - kubernetes.io/pvc-protection


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

  hosts:
    - grafana-keval.duckdns.org

  path: /
  pathType: Prefix

  tls:
    - secretName: grafana-tls
      hosts:
        - grafana-keval.duckdns.org

# service:
#   enabled: true
#   type: NodePort
#   port: 3000
#   targetPort: 3000

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "1"
    memory: 1Gi

podSecurityContext:
  fsGroup: 472

extraInitContainers:
  - name: init-folders
    image: busybox
    command:
      - sh
      - -c
      - |
        mkdir -p /var/lib/grafana/dashboards/OBS
    volumeMounts:
      - name: grafana-provisioning
        mountPath: /var/lib/grafana/dashboards

admin:
  existingSecret: grafana-admin-secret2
  userKey: username
  passwordKey: password

extraVolumes:
  - name: grafana-provisioning
    persistentVolumeClaim:
      claimName: grafana-provisioning

extraVolumeMounts:
  - name: grafana-provisioning
    mountPath: /var/lib/grafana/dashboards
    readOnly: false

extraSecretMounts:
  - name: grafana-aws-secret
    mountPath: /mnt/secrets-store
    secretName: grafana-aws-secret
    readOnly: true

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: prometheus-main
      type: prometheus
      url: https://prometheus-keval.duckdns.org
      uid: asdfasdf20gzkb
      httpMode: 'POST'
      editable: false
      default: true
      orgId: 1
    - name: loki-main
      type: loki
      url: http://loki.devops-tools.svc.cluster.local:3100
      uid: bserfvdf4kpvkf
      httpMode: 'POST'
      editable: false
      orgId: 1
    - name: pyroscope-main
      type: grafana-pyroscope-datasource
      url: http://pyroscope.devops-tools.svc.cluster.local:4040
      uid: gbsradlqxmv4d
      httpMode: 'POST'
      editable: false
      orgId: 1
    - name: jaeger-main
      type: jaeger
      url: http://jaeger.observability.svc.cluster.local:16686
      uid: daasdfaw5nuoc
      httpMode: 'POST'
      editable: false
      orgId: 1
    - name: tempo-main
      type: tempo
      url: http://tempo.devops-tools.svc.cluster.local:3200
      uid: vadfawefasdw5nuoc
      editable: false
      orgId: 2
      jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: bserfvdf4kpvkf
    - name: prometheus-main
      type: prometheus
      url: https://prometheus-keval.duckdns.org
      uid: asdfasdf20gzkb
      httpMode: 'POST'
      editable: false
      default: true
      orgId: 2
    - name: loki-main
      type: loki
      url: http://loki.devops-tools.svc.cluster.local:3100
      uid: bserfvdf4kpvkf
      httpMode: 'POST'
      editable: false
      orgId: 2
    - name: pyroscope-main
      type: grafana-pyroscope-datasource
      url: http://pyroscope.devops-tools.svc.cluster.local:4040
      uid: gbsradlqxmv4d
      httpMode: 'POST'
      editable: false
      orgId: 2
    - name: jaeger-main
      type: jaeger
      url: http://jaeger.observability.svc.cluster.local:16686
      uid: daasdfaw5nuoc
      httpMode: 'POST'
      editable: false
      orgId: 2
    - name: tempo-main
      type: tempo
      url: http://tempo.devops-tools.svc.cluster.local:3200
      uid: vadfawefasdw5nuoc
      editable: false
      orgId: 2
      jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: bserfvdf4kpvkf

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: OBS
        orgId: 1
        type: file
        folder: OBS
        disableDeletion: false
        allowUiUpdates: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/OBS
          foldersFromFilesStructure: true

grafana.ini:
  database:
    type: mysql
    host: $__env{GF_DATABASE_HOST}
    name: $__env{GF_DATABASE_NAME}
    user: $__env{GF_DATABASE_USERNAME}
    password: $__env{GF_DATABASE_PASSWORD}
    ssl_mode: disable
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning