
image:
  registry: docker.io
  repository: grafana/grafana
  tag: "12.4.2"

persistence:
  type: pvc
  enabled: true
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  finalizers:
    - kubernetes.io/pvc-protection

service:
  enabled: true
  type: NodePort
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "1"
    memory: 1Gi

# extraSecretMounts:
#   - name: grafana-mysql
#     secretName: grafana-mysql
#     mountPath: /etc/secrets/grafana-mysql
#     readOnly: true

podSecurityContext:
  fsGroup: 472

extraInitContainers:
  - name: init-folders
    image: busybox
    command:
      - sh
      - -c
      - |
        mkdir -p /var/lib/grafana/dashboards/OBS
    volumeMounts:
      - name: grafana-provisioning
        mountPath: /var/lib/grafana/dashboards

extraVolumes:
  - name: grafana-provisioning
    persistentVolumeClaim:
      claimName: grafana-provisioning

extraVolumeMounts:
  - name: grafana-provisioning
    mountPath: /etc/grafana/provisioning

envFromSecrets:
  - name: grafana-mysql

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.devops-tools.svc.cluster.local:9090
      uid: ffgyyyp220gzkb
      httpMode: 'POST'
      editable: false
      default: true
      orgId: 1
    - name: loki
      type: loki
      url: http://loki.devops-tools.svc.cluster.local:3100
      uid: dfifngdf4kpvkf
      httpMode: 'POST'
      editable: false
      orgId: 1
    - name: pyroscope
      type: grafana-pyroscope-datasource
      url: http://pyroscope.devops-tools.svc.cluster.local:4040
      uid: afifnbjlqxmv4d
      httpMode: 'POST'
      editable: false
      orgId: 1
    - name: jaeger
      type: jaeger
      url: http://jaeger.observability.svc.cluster.local:16686
      uid: dfhgk66yw5nuoc
      httpMode: 'POST'
      editable: false
      orgId: 1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: OBS
        orgId: 1
        type: file
        disableDeletion: false
        allowUiUpdates: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/OBS
          foldersFromFilesStructure: true

grafana.ini:
  database:
    type: mysql
    host: ${MYSQL_HOST}
    name: grafana
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    ssl_mode: disable
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning