[master]
master ansible_host=52.66.233.93 ansible_user=ubuntu ansible_ssh_private_key_file=devops-aws.pem

[workers]
worker1 ansible_host=13.203.68.68 ansible_user=ubuntu ansible_ssh_private_key_file=devops-aws.pem
worker2 ansible_host=13.203.28.119 ansible_user=ubuntu ansible_ssh_private_key_file=devops-aws.pem