- hosts: workers
  become: yes
  tasks:
    - name: Join cluster
      command: kubeadm join 172.31.20.180:6443 --token f7p6cw.7i9q4ju79zi9w0qr --discovery-token-ca-cert-hash sha256:86fb048cba232f3280a4eda8e847d0e04d8aadbdc3b8dce11e660e16d3d412fe