tempo:
  tag: 2.2.2
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: s3-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: s3-secret
        key: AWS_SECRET_ACCESS_KEY
  storage:
    backend: s3
    s3:
      endpoint: "https://s3.ap-south-1.amazonaws.com"
      region: ap-south-1
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      access_key_id: ${AWS_ACCESS_KEY_ID}
      bucket: observability-tempo-keval-demo                           # optional. secret key when using static credentials.
      insecure: false    
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  persistence:
    enabled: true
    size: 5Gi