loki:
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: AWS_ACCESS_KEY_ID

    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: AWS_SECRET_ACCESS_KEY
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks-observability
      ruler: loki-ruler-s3-observability
      admin: loki-admin-observability
    s3:
      endpoint: "https://s3.ap-south-1.amazonaws.com"
      region: ap-south-1
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      access_key_id: ${AWS_ACCESS_KEY_ID}
      signatureVersion: null
      s3ForcePathStyle: false
      insecure: false
      http_config: {}
      # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
      backoff_config: {}
      disable_dualstack: false
    # type: s3
    # s3: 
    #   endpoint: "https://s3.ap-south-1.amazonaws.com"
    #   region: ap-south-1
    #   secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    #   access_key_id: ${AWS_ACCESS_KEY_ID}
    #   bucketnames: 
    #   signatureVersion: v4
    #   s3ForcePathStyle: true

  commonConfig:
    replication_factor: 1
  memberlist: {}
  # schemaConfig:
  #   configs:
  #     - from: 2024-04-01
  #       store: tsdb
  #       object_store: s3
  #       schema: v13
  #       index:
  #         prefix: loki_index_
  #         period: 24h
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  # ingester:
  #   chunk_encoding: snappy
  # tracing:
  #   enabled: true
  # querier:
  #   # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
  #   max_concurrent: 2

#gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix


deploymentMode: SingleBinary

singleBinary:
  persistence:
      whenScaled: Delete
      whenDeleted: Delete
      enableStatefulSetAutoDeletePVC: true
      enableStatefulSetRecreationForSizeChange: false
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      storageClass: ebs-sc
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 12Mi
  # extraEnv:
  #   # Keep a little bit lower than memory limits
  #   - name: GOMEMLIMIT
  #     value: 3750MiB
# resultsCache:
#   enabled: true
#   addresses: dnssrvnoa+_memcached-client._tcp.{{ include "loki.resourceName" (dict "ctx" $ "component" "results-cache") }}.{{ include "loki.namespace" $ }}.svc.{{ .Values.global.clusterDomain }}
#   defaultValidity: 12h
#   timeout: 500ms
#   replicas: 1
#   port: 11211
#   allocatedMemory: 256
#   maxItemMemory: 5
#   connectionLimit: 16384
#   writebackSizeLimit: 126MB
#   writebackBuffer: 500000
chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
  allocatedMemory: 256

# Enable minio for storage
minio:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0
# # Zero out replica counts of other deployment modes
# backend:
#   replicas: 0
# read:
#   replicas: 0
# write:
#   replicas: 0

# ingester:
#   replicas: 0
# querier:
#   replicas: 0
# queryFrontend:
#   replicas: 0
# queryScheduler:
#   replicas: 0
# distributor:
#   replicas: 0
# compactor:
#   replicas: 0
# indexGateway:
#   replicas: 0
# bloomCompactor:
#   replicas: 0
# bloomGateway:
#   replicas: 0
